const dict: Record<string, string> = {
  " (select all that apply)": "（选择所有适用项）",
  "(API key)": "（API 密钥）",
  "(ChatGPT Plus/Pro or API key)": "（ChatGPT Plus/Pro 或 API 密钥）",
  "(Favorite)": "(已收藏)",
  "(Recommended)": "（推荐）",
  "(not answered)": "（未回答）",
  "(tab toggle)": "(Tab 切换)",
  "✓ copied": "✓ 已复制",
  "✓ Enabled": "✓ 已启用",
  "○ Disabled": "○ 已禁用",
  "⋯ Loading": "⋯ 加载中",
  "Action": "操作",
  "Add a favorite model to use this shortcut": "添加收藏模型以使用此快捷方式",
  "Add custom provider": "添加自定义提供商",
  "Allow always": "始终允许",
  "Allow once": "允许一次",
  "Always allow": "始终允许",
  "An unknown error has occurred": "发生未知错误",
  "An unknown error occurred.": "发生未知错误。",
  "API key": "API 密钥",
  "Are you sure you want to restore the reverted messages?": "确定要恢复已撤销的消息吗？",
  "Are you sure you want to share it?": "确定要分享吗？",
  "Ask a question": "提问",
  "Ask questions": "询问问题",
  "Ask questions...": "询问问题中...",
  "Ask the user a question": "向用户提问",
  "Asking questions...": "询问问题中...",
  "Authorization code": "授权码",
  "Background subagents": "后台子智能体",
  "BUILD": "构建",
  "Built-in": "内置",
  "Built-in plugin": "内置插件",
  "Cancel": "取消",
  "Check npm registry/auth settings and try again.": "请检查 npm 注册表/认证设置后重试。",
  "Click to collapse": "点击折叠",
  "Click to expand": "点击展开",
  "Close dialog": "关闭对话框",
  "Close viewer": "关闭查看器",
  "Collapse thinking": "折叠思考过程",
  "Code": "代码",
  "Commands": "命令",
  "Compact session": "压缩会话",
  "Compaction": "压缩",
  "Confirm": "确认",
  "Confirm Redo": "确认重做",
  "Connect a provider to summarize this session": "请先连接提供商以压缩会话",
  "Connect provider": "连接提供商",
  "Continue after repeated failures": "重复失败后继续",
  "Copied to clipboard": "已复制到剪贴板",
  "Copied worktree path": "已复制工作目录路径",
  "Copy": "复制",
  "Copy and exit": "复制并退出",
  "Copy last assistant message": "复制最近助手消息",
  "Copy provider code": "复制提供商代码",
  "Copy session transcript": "复制会话记录",
  "Copy share link": "复制分享链接",
  "Could not load orgs": "无法加载组织",
  "Could not load project directories": "无法加载项目目录",
  "Creating copy": "创建副本中",
  "Creating session": "创建会话中",
  "Creating workspace failed": "创建工作区失败",
  "Current": "当前",
  "Custom provider": "自定义提供商",
  "Cycle model variant": "切换模型变体",
  "Date": "日期",
  "Debug": "调试",
  "Debug info copied to clipboard": "调试信息已复制到剪贴板",
  "Default": "默认",
  "Delete file ": "删除文件 ",
  "Delete working copy?": "删除工作副本？",
  "Delete workspace": "删除工作区",
  "Delegating...": "委派中...",
  "Deleting...": "删除中...",
  "Description": "说明",
  "Directory": "目录",
  "Disable code concealment": "关闭代码折叠",
  "Do you want to move these changes with the session?": "要将这些更改随会话一起移动吗？",
  "Edit file ": "编辑文件 ",
  "Enable code concealment": "开启代码折叠",
  "Enter filename": "输入文件名",
  "Error": "错误",
  "EXIT": "退出",
  "Exa Web Search": "Exa 网页搜索",
  "Expand all folders": "展开所有文件夹",
  "Expand thinking": "展开思考过程",
  "Export Options": "导出选项",
  "Export session transcript": "导出会话记录",
  "Existing Workspace": "已有工作区",
  "External": "外部",
  "Failed to copy session transcript": "复制会话记录失败",
  "Failed to copy to clipboard": "复制到剪贴板失败",
  "Failed to copy URL to clipboard": "复制链接失败",
  "Failed to create workspace": "创建工作区失败",
  "Failed to delete project copy": "删除项目副本失败",
  "Failed to delete session": "删除会话失败",
  "Failed to delete workspace": "删除工作区失败",
  "Failed to load diff": "加载差异失败",
  "Failed to share session": "分享会话失败",
  "Failed to unshare session": "取消分享失败",
  "Fetch URL": "获取 URL",
  "Fetching from the web...": "从网页获取中...",
  "File": "文件",
  "File Changes Found": "发现文件更改",
  "Finishing startup...": "完成启动中...",
  "First item": "第一项",
  "First message": "第一条消息",
  "Focus file tree": "聚焦文件树",
  "Fork": "分叉",
  "Fork session": "分叉会话",
  "Free": "免费",
  "Full session": "完整会话",
  "Getting started": "快速开始",
  "Half page down": "下翻半页",
  "Half page up": "上翻半页",
  "Heap snapshot written to": "堆快照已写入到",
  "Help": "帮助",
  "Hide generic tool output": "隐藏通用工具输出",
  "Hide sidebar": "隐藏侧边栏",
  "Hide timestamps": "隐藏时间戳",
  "Hide tool details": "隐藏工具详情",
  "ID": "ID",
  "Internal": "内置",
  "Install plugin": "安装插件",
  "Installing plugin...": "安装插件中...",
  "Invalid code": "无效的验证码",
  "Invalid model format": "模型格式无效",
  "Jump to last user message": "跳转到最近用户消息",
  "Jump to message": "跳转到消息",
  "Jump to next diff file": "跳转到下一个差异文件",
  "Jump to previous diff file": "跳转到上一个差异文件",
  "Jump to the first which-key binding": "跳转到第一个快捷键",
  "Jump to the last which-key binding": "跳转到最后一个快捷键",
  "Jump to the next diff hunk": "跳转到下一个差异代码块",
  "Jump to the previous diff hunk": "跳转到上一个差异代码块",
  "Key": "按键",
  "Last item": "最后一项",
  "Last message": "最后一条消息",
  "Line down": "下移一行",
  "Line up": "上移一行",
  "Loaded": "已加载",
  "Loading diff...": "加载差异中...",
  "Loading orgs...": "加载组织中...",
  "Loading plugins...": "加载插件中...",
  "Loading project directories...": "加载项目目录中...",
  "Loading skill...": "加载技能中...",
  "Local": "本地",
  "Low cost subscription for everyone": "面向所有人的低成本订阅",
  "Main branch": "主分支",
  "Mark reviewed": "标记已审阅",
  "Message Actions": "消息操作",
  "Message copied to clipboard!": "消息已复制到剪贴板！",
  "Model": "模型",
  "Model stopped responding": "模型停止响应",
  "Models loading": "加载模型中...",
  "Move file ": "移动文件 ",
  "Move keyboard focus between the file tree and patch pane": "在文件树和补丁面板之间切换键盘焦点",
  "Move session": "移动会话",
  "Moving session": "移动会话中",
  "Next": "下一个",
  "Next child session": "下一个子会话",
  "Next file": "下一个文件",
  "Next hunk": "下一个代码块",
  "Next item": "下一项",
  "Next key binding group": "下一组快捷键",
  "Next message": "下一条消息",
  "No assistant messages found": "未找到助手消息",
  "No diff provided": "未提供差异",
  "No diff!": "无差异！",
  "No matching items": "无匹配项",
  "No orgs found": "未找到组织",
  "No patch available for this file.": "此文件没有可用的补丁。",
  "No project directories found": "未找到项目目录",
  "No provider selected": "未选择提供商",
  "No queued prompts": "无队列提示",
  "No reachable bindings": "无可触发的快捷键",
  "No results found": "未找到结果",
  "No skills available": "暂无可用技能",
  "No skills found": "未找到技能",
  "No stack trace available.": "无堆栈信息。",
  "No subagents found": "未找到子智能体",
  "No text content found in last assistant message": "最近助手消息中无文本内容",
  "No text parts found in last assistant message": "最近助手消息中无文本内容",
  "No variants available": "无可用变体",
  "None": "无",
  "OAuth authorization failed. Try /connect again.": "OAuth 授权失败。请重试 /connect。",
  "OS": "操作系统",
  "Open": "打开",
  "Open command palette": "打开命令面板",
  "Open without saving": "打开但不保存",
  "OpenCode Go is a $10 per month subscription that provides reliable access to popular open coding models with generous usage limits.": "OpenCode Go 是每月 $10 的订阅服务，提供可靠的热门开源编程模型访问和慷慨的使用额度。",
  "OpenCode Zen gives you access to all the best coding models at the cheapest prices with a single API key.": "OpenCode Zen 让您通过一个 API 密钥以最低价格访问所有最佳编程模型。",
  "OpenCode includes free models so you can start immediately.": "OpenCode 包含免费模型，您可以立即开始使用。",
  "Open editor": "打开编辑器",
  "Other": "其他",
  "Package has no TUI target to load in this app.": "该包没有可用于此应用的 TUI 目标。",
  "Parallel Web Search": "并行网页搜索",
  "Parent": "父级",
  "Patch": "补丁",
  "Patch failed": "补丁失败",
  "Path: ": "路径：",
  "Patterns": "模式",
  "Permission": "权限",
  "Permission needs input": "权限需要输入",
  "Permission required": "需要权限",
  "Permissions": "权限",
  "Plugin package name is required": "需要插件包名称",
  "Plugins": "插件",
  "Popular": "热门",
  "Popular providers": "热门提供商",
  "Preparing edit...": "准备编辑...",
  "Preparing patch...": "准备补丁中...",
  "Preparing write...": "准备写入中...",
  "Prev": "上一个",
  "Previous": "上一个",
  "Previous child session": "上一个子会话",
  "Previous file": "上一个文件",
  "Previous hunk": "上一个代码块",
  "Previous item": "上一项",
  "Previous key binding group": "上一组快捷键",
  "Previous message": "上一条消息",
  "Press ctrl+c again to exit": "再次按 Ctrl+C 退出",
  "Provider id": "提供商 ID",
  "Provider ids must start with a lowercase letter or number and only use lowercase letters, numbers, hyphens, and underscores": "提供商 ID 必须以小写字母或数字开头，且仅使用小写字母、数字、连字符和下划线",
  "Providers": "提供商",
  "Query: ": "查询：",
  "Queued prompts": "队列提示",
  "Question needs input": "需要输入",
  "Quit the diff viewer": "退出差异查看器",
  "Read file": "读取文件中...",
  "Reading file...": "读取文件中...",
  "Recent": "最近",
  "Redo": "重做",
  "Refresh": "刷新",
  "Reject": "拒绝",
  "Reject permission": "拒绝权限",
  "Rename Session": "重命名会话",
  "Rename session": "重命名会话",
  "Report issue": "报告问题",
  "Restart": "重启",
  "Restore to new workspace": "恢复到新工作区",
  "Retrying": "重试中",
  "Revert": "撤销",
  "Review": "审阅",
  "Run": "运行",
  "Run shell command": "运行 Shell 命令",
  "SHELL": "Shell",
  "Session ID": "会话 ID",
  "Session aborted": "会话已中止",
  "Session done": "会话完成",
  "Session error": "会话错误",
  "Session exported to": "会话已导出到",
  "Session not found": "会话未找到",
  "Session transcript copied to clipboard!": "会话记录已复制到剪贴板！",
  "Session unshared successfully": "取消分享成功",
  "Sessions": "会话",
  "Search": "搜索",
  "Search content": "搜索内容中...",
  "Search the web": "搜索网页中...",
  "Search web": "搜索网页中...",
  "Searching content...": "搜索内容中...",
  "Searching web...": "搜索网页中...",
  "Select agent": "选择智能体",
  "Select auth method": "选择认证方式",
  "Select item": "选择",
  "Select model": "选择模型",
  "Select subagent": "选择子智能体",
  "Select variant": "选择变体",
  "Show changes compared to main branch": "显示与主分支的差异",
  "Show changes from the last assistant turn": "显示最近助手轮次的变更",
  "Show current git changes": "显示当前 git 变更",
  "Show generic tool output": "显示通用工具输出",
  "Show key bindings": "显示快捷键",
  "Show keyboard shortcuts with": "按以下键显示快捷键",
  "Show or hide the file tree sidebar": "显示或隐藏文件树侧边栏",
  "Show sidebar": "显示侧边栏",
  "Show the next which-key group": "显示下一组快捷键",
  "Show the previous which-key group": "显示上一组快捷键",
  "Show timestamps": "显示时间戳",
  "Show tool details": "显示工具详情",
  "Shell command": "Shell 命令",
  "Shell mode": "Shell 模式",
  "Skill: ": "技能：",
  "Skills": "技能",
  "Skills loading": "加载技能中...",
  "Stash": "暂存",
  "Status": "状态",
  "Subagent": "子智能体",
  "Subagent Actions": "子智能体操作",
  "Suggested": "建议",
  "Switch between one selected patch and all patches": "在单个选中补丁和所有补丁之间切换",
  "Switch between split and unified diff layout": "在分栏和统一差异布局之间切换",
  "Switch model": "切换模型",
  "Switch model variant": "切换模型变体",
  "Switch org": "切换组织",
  "Switch source": "切换来源",
  "Tab": "Tab",
  "Task: ": "任务：",
  "Terminal": "终端",
  "The current model does not support any variants.": "当前模型不支持任何变体。",
  "The current session was deleted": "当前会话已被删除",
  "This keeps the session running despite repeated failures.": "这将使会话在重复失败后继续运行。",
  "This only stores a credential. Configure the provider in opencode.json to use it.": "这仅存储凭据。请在 opencode.json 中配置提供商以使用它。",
  "This session is attached to a workspace that is no longer available.": "此会话关联的工作区已不可用。",
  "This will allow the following patterns until OpenCode is restarted": "这将允许以下模式，直到 OpenCode 重启",
  "This working copy has file changes. Do you want to delete it anyway?": "此工作副本有文件更改。确定要删除吗？",
  "Thinking": "思考中",
  "Thought": "思考",
  "Theme": "主题",
  "Themes": "主题",
  "Timeline": "时间线",
  "Toggle file tree": "切换文件树",
  "Toggle key bindings layout": "切换快捷键布局",
  "Toggle patches": "切换补丁",
  "Toggle pending key preview": "切换待定按键预览",
  "Toggle reviewed state for the selected file": "切换选中文件的审阅状态",
  "Toggle session scrollbar": "切换会话滚动条",
  "Toggle view": "切换视图",
  "Toggle which-key overlay": "切换快捷键覆盖层",
  "Tool: ": "工具：",
  "Tools": "工具",
  "Type your own answer": "输入自定义答案",
  "URL: ": "URL：",
  "Unable to Warp Session": "无法迁移会话",
  "Undo previous message": "撤销上一条消息",
  "Unknown": "未知",
  "Unknown plugin route:": "未知插件路由：",
  "Unshare session": "取消分享",
  "Update Available": "有可用更新",
  "Update Complete": "更新完成",
  "Update Failed": "更新失败",
  "Updating todos...": "更新待办中...",
  "Use @agent-name in prompts to invoke specialized subagents": "在提示中使用 @agent-name 调用专用子智能体",
  "Use the local project": "使用本地项目",
  "Version": "版本",
  "View all providers": "查看所有提供商",
  "View all workspaces": "查看所有工作区",
  "View subagents": "查看子智能体",
  "Warp": "迁移",
  "Waiting for authorization...": "等待授权中...",
  "Waiting for permission event...": "等待权限事件...",
  "Web Search": "网页搜索",
  "Working tree": "工作树",
  "Working tree: ": "工作树：",
  "Workspace Unavailable": "工作区不可用",
  "Would you like to restore this session into a new workspace?": "是否将此会话恢复到新工作区？",
  "Write file": "写入文件中...",
  "Writing command...": "写入命令中...",
  "Write file: ": "写入文件：",
  "Write a plugin to restrict what OpenCode can read": "创建插件以限制 OpenCode 可读取的内容",
  "active": "运行中",
  "add": "添加",
  "agent": "智能体",
  "again to interrupt": "再次中断",
  "attempt": "尝试",
  "background": "后台",
  "cancel": "取消",
  "cancelled": "已取消",
  "cmd": "命令",
  "confirm": "确认",
  "copy": "复制",
  "create a new session": "创建新会话",
  "current": "当前",
  "delete": "删除",
  "disabled": "已禁用",
  "dismiss": "关闭",
  "done": "完成",
  "don't show again": "不再显示",
  "files": "个文件",
  "global": "全局",
  "go home": "返回首页",
  "inactive": "未激活",
  "install": "安装",
  "interrupt": "中断",
  "last turn": "上一轮",
  "local": "本地",
  "main branch": "主分支",
  "message reverted": "条消息已撤销",
  "message text to clipboard": "复制消息文本到剪贴板",
  "minimize": "最小化",
  "move": "移动",
  "new": "新建",
  "next file": "下一个文件",
  "next hunk": "下一个代码块",
  "next": "下一个",
  "no diff": "无差异",
  "no": "否",
  "none": "无",
  "normal": "普通",
  "of": "/",
  "previous file": "上一个文件",
  "previous hunk": "上一个代码块",
  "queued": "已排队",
  "recent": "最近",
  "refresh": "刷新",
  "rename": "重命名",
  "restore": "恢复",
  "results": "个结果",
  "running": "运行中",
  "select": "选择",
  "subagents": "子智能体",
  "submit": "提交",
  "switch source": "切换来源",
  "switch": "切换",
  "tab": "Tab",
  "task": "任务",
  "the subagent's session": "子智能体会话",
  "toggle": "切换",
  "to restore": "以恢复",
  "undo messages and file changes": "撤销消息和文件更改",
  "view subagents": "查看子智能体",
  "yes": "是",
}

export function zh(en: string): string {
  return dict[en] ?? en
}
